name: build app
on:
  push:
    branches:
      - '*'
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd app && npm install && npm run build
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd server && npm install && npx -y tsc