name: build app
on:
  push:
    branches:
      - '*'
jobs:
  deploy-webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd app && npm install && npm run build